### ISSUE TITLE
Missing author in AMP pages

### ISSUE THREAD

**Issue by willsmith7** [schemapress/Schema#11]
Hi, i installed your plugin but it gives me "missing author" in every AMP page. Below one of my AMP pages:

https://goo.gl/DP0aeS

How can i fix?

P.S. i opened a thread in the support forum too, but it seems inactive, even if i am not sure of it. Sorry for double thread

**Comment by schemapress** [comment]
Just checked, it's working fine on my test site. Also, I tested the page you've mentioned, it seems to be ok!
