### ISSUE TITLE
Performances issue on high traffic websites due to UPDATE SQL statements

### ISSUE THREAD

**Issue by seyfro** [schemapress/Schema#23]
Hi, 
first thanks for providing your plugin - I use it on a high traffic website and disovered an issue though in this respect:

within `/includes/json/schema-output.php` on line 137 and 138 two SQL update statements are called on each post view:
```
update_post_meta( $post->ID, '_schema_json', $json );
update_post_meta( $post->ID, '_schema_json_timestamp', $pttimestamp );
```
This lead to an issue with our database server, when 20.000 concurrent users accessed the site.
As a workaround we moved those two lines up to line 122, so that those are only executed within `if ( !isset($json) || empty($json) ) {`

If I understand your code here correctly, I do not see an added value if those two update_post_meta-Queries are executed on each post view.

If I am wrong here, please disregard my ticket.
thx,

Robert

**Comment by hishaman** [comment]
This function is required, here is how it works:

The Schema plugin saves the generated json-ld in post meta on the first visit -only- to be pulled and used latter when the page gets more visits.

So, this function shouldn't run each time.

Sorry for late reply!

**Comment by seyfro** [comment]
thx for the explanation!
