### ISSUE TITLE
Description has predefined text. It's not clear how to change it

### ISSUE THREAD

**Issue by dskarasev** [schemapress/Schema#7]
Page source contain following code (have a look bellow). Description tag contains predefined example text. Seems it's not coming from page. There is no settings to define it

<script type="application/ld+json">{"@context":"http:\/\/schema.org","@type":"AboutPage","mainEntityOfPage":{"@type":"WebPage","@id":"http:\/\/alpinresort.eu\/"},"url":"http:\/\/alpinresort.eu\/","headline":"Home (DE)","publisher":{"@type":"Organization","name":"Alpinresort Dam\u00fcls","logo":{"@type":"ImageObject","url":"","width":600,"height":60}},"description":"This is an example page. It's different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:"}</script>

**Comment by hishaman** [comment]
This is mostly a caching issue, you will need to clear the caching plugin if you are using any. Let m know if this solve the issue.
